name: Build and package python apps

on: push

jobs:
  build-mac:
    runs-on: macos-latest
    env:
      PYTHONVERSION: "3.11.7"
      MACOSX_DEPLOYMENT_TARGET: "14.3"
      PYI_BUILD_MODE: "onedir"

    steps:
    - uses: actions/checkout@v2

    - name: Cache Python download
      id: cache-python-download
      uses: actions/cache@v3
      with:
        path: ~/python.pkg
        key: macOS-Python-${{ env.PYTHON_VERSION }}

    - name: Get Python
      run: |
       curl https://www.python.org/ftp/python/${PYTHONVERSION}/python-${PYTHONVERSION}-macos11.pkg -o ~/python.pkg

    - name: Install Python
      run: sudo installer -pkg ~/python.pkg -target /

    - name: Install Python dependencies and build
      run: |
        python3 --version
        pip3 install --upgrade pip wheel
        pip3 install pyinstaller
        pip3 install -r requirements.txt
        pyinstaller app.spec
      
    - name: Log files
      run: |
        ls dist
        ls dist/PromptDebugger
        mkdir app
        mv ./dist/PromptDebugger.app ./app/PromptDebugger.app
        hdiutil create -srcfolder ./app PromptDebugger.dmg

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: PromptDebugger.dmg
        asset_name: PromptDebugger.dmg
        tag: latest-builds
        overwrite: true
        
  build-linux:
    runs-on: ubuntu-latest
    env:
      PYI_BUILD_MODE: "onefile"

    steps:
    - uses: actions/checkout@v2

    - name: Install requirements
      run: |
        pip3 install pyinstaller
        pip3 install -r requirements.txt
    - name: Build
      run: pyinstaller app.spec
      
    - name: Log files
      run: |
        ls dist

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: dist/PromptDebugger
        asset_name: PromptDebugger
        tag: latest-builds
        overwrite: true
  
  build-windows:
    runs-on: windows-latest
    env:
      PYI_BUILD_MODE: "onefile"
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Python dependencies and build
      run: |
        python3 --version
        pip install --upgrade pip wheel
        pip install pyinstaller
        pip install -r requirements.txt
        pyinstaller app.spec
      
    - name: Log files
      run: |
        ls dist

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: dist/PromptDebugger.exe
        asset_name: PromptDebugger.exe
        tag: latest-builds
        overwrite: true
